### ISSUE TITLE
Missing reference to layers/bg.json

### ISSUE THREAD

**Issue by jacmendt** [lyrk/lyrk-mapstyle#2]
In the [mapstyle configuration](https://github.com/lyrk/lyrk-mapstyle/blob/master/project.mml) is a layer `background`, which reference the file `layers/bg.geonjson`. This json is neither in the repository yet there is a reference to an external resource. Where could i find it?

**Comment by ubahnverleih** [comment]
Oh, sorry i missed to include it to the project.

**Comment by ubahnverleih** [comment]
Sorry, fixed in 7acf0819384f50773957a6cf75be14d21ad18da7
