### ISSUE TITLE
Postgis Plugin: ERROR:  column "addr_housenumber" does not exist

### ISSUE THREAD

**Issue by huna79** [lyrk/lyrk-mapstyle#5]
System info:
- PostgreSQL 10.6
- Postgis 2.5.2
- imposm-0.8.1
- magnacarto-1.1.0
- lyrk-mapstyle-2.0

Tiles for zoom levels 17 and higher cannot be rendered because of this error:
Postgis Plugin: ERROR:  column "addr_housenumber" does not exist

Select statement:
SELECT ST_AsBinary("geometry") AS geom,"addr_housenumber","name" FROM ( SELECT geometry, type, type AS "addr:housenumber"
	FROM osm_housenumbers_ways
	WHERE type NOT IN ('0','false', 'no')
	UNION
	SELECT geometry, type,
	  CASE
	    WHEN name NOT LIKE '' /*AND length(name)<10 THEN name*/ THEN  ''
	    ELSE type
	  END AS "addr:housenumber"
	FROM osm_housenumbers
	WHERE type NOT IN ('0','false', 'no')
	) AS data WHERE "geometry" && ST_SetSRID('BOX3D(1714482.544436503 5941144.460493609,1717234.277454771 5943896.193511877)'::box3d, 3857)

**Comment by thomersch** [comment]
Thank you for reporting 👍

Have you imported using the provided mapping file?

**Comment by huna79** [comment]
Yes, I used the file mapping.json from lyrk-mapstyle-2.0/imposm.

**Comment by GeOSMRob** [comment]
Hi,

This is an Bug. In the project.mml the column is referenced by SQL. 

https://github.com/lyrk/lyrk-mapstyle/blob/master/project.mml#L1076

Can you fix it locally if you adjust the subselect reference in project.mml? 

This is a SQL-Select:
```sql
(
SELECT geometry, type, name, type AS \"addr_housenumber\" FROM osm_housenumbers_ways WHERE type NOT IN ('0','false', 'no')
UNION
SELECT geometry, type, name, CASE WHEN name NOT LIKE '' /*AND length(name)<10 THEN name*/ THEN  '' ELSE type  END AS \"addr_housenumber\" FROM osm_housenumbers WHERE type NOT IN ('0','false', 'no')
) AS data 
```
Because the label.mss refers to a table column with "[addr_housenumber]"

https://github.com/lyrk/lyrk-mapstyle/blob/master/labels.mss#L643

You can try it.

**Comment by huna79** [comment]
Thanks alot, now it's ok!

**Comment by thomersch** [comment]
Can one of you fix it, so others don't run into the same issue?

**Comment by GeOSMRob** [comment]
Fixed a bug.
